/*
 * CSOLUTION generated file: DO NOT EDIT!
 * Generated by: csolution version 2.6.0
 *
 * Project: 'Demo.Debug+AVH' 
 * Target:  'Debug+AVH' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "SSE300MPS3.h"

/* ARM::CMSIS Driver:USART@1.0.0 */
#define RTE_USART0      1

/* ARM::CMSIS:RTOS2:FreeRTOS&Cortex-M@11.1.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_FreeRTOS        /* CMSIS-RTOS2 FreeRTOS */
/* ARM::Device:Native Driver:IO@1.1.0 */
#define RTE_MPS3_IO      1
/* ARM::Device:Native Driver:SysCounter@1.1.0 */
#define RTE_SYSCOUNTER      1
/* ARM::Device:Native Driver:Timeout@1.0.0 */
#define RTE_TIMEOUT      1
/* ARM::RTOS&FreeRTOS:Config&CMSIS RTOS2@11.1.0 */
#define RTE_RTOS_FreeRTOS_CONFIG_RTOS2  /* RTOS FreeRTOS Config for CMSIS RTOS2 API */
/* ARM::RTOS&FreeRTOS:Core&Cortex-M@11.1.0 */
#define RTE_RTOS_FreeRTOS_CORE          /* RTOS FreeRTOS Core */
/* ARM::RTOS&FreeRTOS:Event Groups@11.1.0 */
#define RTE_RTOS_FreeRTOS_EVENTGROUPS   /* RTOS FreeRTOS Event Groups */
/* ARM::RTOS&FreeRTOS:Heap&Heap_5@11.1.0 */
#define RTE_RTOS_FreeRTOS_HEAP_5        /* RTOS FreeRTOS Heap 5 */
/* ARM::RTOS&FreeRTOS:Stream Buffer@11.1.0 */
#define RTE_RTOS_FreeRTOS_STREAM_BUFFER /* RTOS FreeRTOS Stream Buffers */
/* ARM::RTOS&FreeRTOS:Timers@11.1.0 */
#define RTE_RTOS_FreeRTOS_TIMERS        /* RTOS FreeRTOS Timers */
/* ARM::Security:mbed TLS@2.24.0 */
#define RTE_Security_mbedTLS            /* Security mbed TLS */
/* Keil::CMSIS Driver:Ethernet:ETH_LAN91C111@1.1.0 */
#define RTE_Drivers_ETH_LAN91C111       /* Driver ETH_LAN91C111 */
/* MDK-Packs::IoT Utility:Socket:VSocket@1.0.0 */
#define RTE_IoT_Socket                  /* IoT Socket */
#define RTE_IoT_Socket_VSocket          /* IoT Socket: VSocket */


#endif /* RTE_COMPONENTS_H */
